### ISSUE TITLE
Revise the Guidance document as a part of preparation for the next data call

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/biodiversity-portal#9] opened 2018-02-01 09:10 UTC
Revise the ‘Guidance’ document based on recent changes in format and features (ICES) and decisions (Ian)

**Comment by neil-ices-dk** [comment] 2020-11-09 14:10
@IanMitchell1 to send the latest version of document for 2020 call;

**Comment by cmspinto** [comment] 2020-11-20 13:20
Hi @IanMitchell1 all the links needed are in this page: http://biodiversity.ices.dk/ 
We have updated the template to include the new field.


[OSPAR_Birds_Reporting_Format - 2020-11-09.zip](https://github.com/ices-tools-dev/biodiversity-portal/files/5573708/OSPAR_Birds_Reporting_Format.-.2020-11-09.zip)

**Comment by neil-ices-dk** [comment] 2020-11-27 09:19
Duplicate of #8

**Closed as completed by neil-ices-dk** 2020-11-27 09:19 UTC
Labels: enhancement
